[package]
name = "simple_comics_viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdk4 = "0.9"
gtk4 = "0.9"
gio = "0.20"
glib = "0.20"
libarchive3-sys-by-madosuki = { git = "https://github.com/madosuki/libarchive3-sys-by-madosuki"}
libarchive_extractor-rs = { git = "https://github.com/madosuki/libarchive_extractor-rs" }
anyhow = "1.0.91"
tokio = { version = "1", features = ["full"] }
