[package]
name = "simple_comics_viewer"
version = "0.0.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = "0.10"
libarchive3-sys-by-madosuki = { git = "https://github.com/madosuki/libarchive3-sys-by-madosuki"}
libarchive_extractor-rs = { git = "https://github.com/madosuki/libarchive_extractor-rs" }
anyhow = "1.0.99"
mupdf = { version = "0.5.0", features = ["sys-lib"]}
