[package]
name = "simple_comics_viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdk-pixbuf-sys = "0.17"
gdk4 = "0.6"
gtk4 = "0.6"
gio = "0.17"
glib = "0.17"
gdk-pixbuf = "0.17"
libarchive3-sys-by-madosuki = { git = "https://github.com/madosuki/libarchive3-sys-by-madosuki"}
libarchive_extractor-rs = { git = "https://github.com/madosuki/libarchive_extractor-rs" }
anyhow = "1.0.75"
tokio = { version = "1", features = ["full"] }